website/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/album_id/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album_add'),

    # music/album/id/update
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album_update'),

    # music/album/id/delete
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album_delete'),

    #music/album/addsong
    url(r'^album/(?P<pk>[0-9]+)/addsong/$', views.SongCreate.as_view(), name='song_add'),

]

website/website/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=50)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=300)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.album.pk})

    def __str__(self):
        return self.song_title + ' : ' + str(self.album)

website/music/views.py
from django.views import generic
from .models import Album
from .models import Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title', 'genre', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class SongCreate(CreateView):
    model = Song
    fields = ['album','file_type', 'song_title']

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% block title %} Add Album {% endblock %}

{% block body %}
 <div class="container">
     <div class="row">
         <div class="col-sm-12">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'music/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>

                     </form>
                 </div>
             </div>
         </div>

     </div>
 </div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}NIXHAT{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" >
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse" >
    <div class="container-fluid">

        <!--  LOGO  -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">NIXHAT</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" about="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" >
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

             <ul class="nav navbar-nav navbar-right" >
                <li class="">
                    <a href="{% url 'music:album_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    {% block body %}
    {% endblock %}

</body>
</html>

website/music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %} Album Detail {% endblock %}
{% block body %}
 <div class="container">
     <div class="row">
         <div class="col-sm-12">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <div class="col-sm-4">
                    <img src="{{album.album_logo.url}}" height="300" width="300">

                    <h1>{{album.album_title}}  <small>{{album.genre}}</small></h1>
                    <h3>{{album.artist}}</h3>

                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                        {% for song in album.song_set.all%}
                            <input type="radio" id="song{{forloop.counter}}" name="song" value="{{song.id}}" >
                            <label for="song{{forloop.counter}}">
                                {{song.song_title}}
                                {%if song.is_favorite%}
                                    <img src="http://www.caption.me/core/images/star.png" />
                                {% endif %}
                            </label><br>
                        {% endfor %}
                     </div>
                     <a href="{% url 'music:song_add' album.id %}" class="btn btn-primary">Add Song</a>
                 </div>
             </div>
         </div>
     </div>
 </div>
{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
         <div class="col-sm-offset-2 col-sm-10">
             <span class="text-danger" small>{{field.errors}}</span>
         </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>

{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}


{% block body %}

        <div class="container">
            <div class="row">
        {% for album in all_albums %}
                <div class="col-sm-4">

                    <div class="panel panel-default">
                         <div class="panel-body">

                                <img src="{{album.album_logo.url}}" width="300" height="300">

                             <h2>{{album.album_title}}</h2>
                             <a href="{% url 'music:detail' album.id %}" class="btn btn-primary">View Details</a>
                             <form action="{% url 'music:album_delete' album.id %}" method="post">
                                 {% csrf_token %}
                                 <input type="hidden" name="album_id" value="{{album.id}}" />
                                 <button type="submit" class="btn btn-default">
                                    <span class="glyphicon glyphicon-trash"></span>
                                 </button>

                             </form>

                             <a href="#" class="btn btn-default"><span class="glyphicon glyphicon-star-empty"></span></a>
                         </div>
                    </div>
                </div>
        {% endfor %}
            </div>
        </div>
{% endblock %}

website/music/templates/music/song_form.html
{% extends 'music/base.html' %}

{% block title %} Add Song {% endblock %}

{% block body %}
 <div class="container">
     <div class="row">
         <div class="col-sm-12">
             <div class="panel panel-default">
                 <div class="panel-body">
                     <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                         {% csrf_token %}
                         {% include 'music/form-template.html' %}
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button type="submit" class="btn btn-success">Submit</button>
                             </div>
                         </div>

                     </form>
                 </div>
             </div>
         </div>

     </div>
 </div>
{% endblock %}